CREATE TABLE EMPLOYEE (
  ID SERIAL PRIMARY KEY,
  NAME VARCHAR(20) NOT NULL,
  SURNAME VARCHAR(20) NOT NULL,
  BIRTH_DAY DATE NOT NULL
);

CREATE TABLE EMPLOYEE_SALARY (
    ID SERIAL PRIMARY KEY,
    EMPLOYEE_ID INTEGER REFERENCES EMPLOYEE(ID) ON DELETE SET NULL,
    SALARY INTEGER NOT NULL,
    MONTH INT(2) NOT NULL
);
